version: '3'
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    environment:
      - LDAP_ORGANISATION=TFG iban
      - LDAP_DOMAIN=ibantfg.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=LDAPapTFG
      - LDAP_CONFIG_PASSWORD=LDAPcpTFG
      - "LDAP_BASE_DN=dc=ibantfg,dc=com"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=ibantfg.com.ca.crt
    volumes:
      - ./ldapConf/compartido:/root/compartido
    networks:
      - openldap_n

  ssh_log:
    image: alpine:latest
    container_name: ssh_log
    command: sh -c "nc -l -p 514 >> /var/log/ssh_access.log"
    volumes:
      - ./ldapConf/log:/var/log
    networks:
      - openldap_n

  client1:
    image: ibantxu12/uldapyssh
    container_name: client1
    hostname: cliente1
    ports:
      - 221:22
    volumes:
      - ./ldapConf/scriptsClientes:/usr/local/bin/scripts
      - ./ldapConf/pam:/etc/pam.d/sshd
      - ./ldapConf/sshd_config:/etc/ssh/sshd_config
    networks:
      - openldap_n
    command: ["/usr/local/bin/scripts/start_services.sh"]

  client2:
    image: ibantxu12/uldapyssh
    container_name: client2
    hostname: cliente2
    ports:
      - 222:22
    volumes:
      - ./ldapConf/scriptsClientes:/usr/local/bin/scripts
      - ./ldapConf/pam:/etc/pam.d/sshd
    networks:
      - openldap_n
    command: ["/usr/local/bin/scripts/start_services.sh"]

  client3:
    image: ibantxu12/uldapyssh
    container_name: client3
    hostname: cliente3
    ports:
      - 223:22
    volumes:
      - ./ldapConf/scriptsClientes:/usr/local/bin/scripts
      - ./ldapConf/pam:/etc/pam.d/sshd
    networks:
      - openldap_n
    command: ["/usr/local/bin/scripts/start_services.sh"]

  client4:
    image: ibantxu12/uldapyssh
    container_name: client4
    hostname: cliente4
    ports:
      - 224:22
    volumes:
      - ./ldapConf/scriptsClientes:/usr/local/bin/scripts
      - ./ldapConf/pam:/etc/pam.d/sshd
    networks:
      - openldap_n
    command: ["/usr/local/bin/scripts/start_services.sh"]

  client5:
    image: ibantxu12/uldapyssh
    container_name: client5
    hostname: cliente5
    ports:
      - 225:22
    volumes:
      - ./ldapConf/scriptsClientes:/usr/local/bin/scripts
      - ./ldapConf/pam:/etc/pam.d/sshd
    networks:
      - openldap_n
    command: ["/usr/local/bin/scripts/start_services.sh"]

networks:
  openldap_n:
    driver: bridge