version: '3'
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    environment:
      - LDAP_ORGANISATION=TFG iban
      - LDAP_DOMAIN=ibantfg.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=LDAPapTFG
      - LDAP_CONFIG_PASSWORD=LDAPcpTFG
      - "LDAP_BASE_DN=dc=ibantfg,dc=com"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=ibantfg.com.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=pepito
      - LDAP_READONLY_USER_PASSWORD=pepitoPass
    ports:
      - 389:389
      - 636:636
    volumes:
      - ../ldapConf/certificates:/container/service/slapd/assets/certs
      - ../ldapConf/slapd/database:/var/lib/ldap
      - ../ldapConf/slapd/config:/etc/ldap/slapd.d
    networks:
      - openldap_n

  client1:
    image: ubuntu:latest
    container_name: client1
    hostname: cliente1
    networks:
      - openldap_n
    command: tail -f /dev/null

  client2:
    image: ubuntu:latest
    container_name: client2
    hostname: cliente2
    networks:
      - openldap_n
    command: tail -f /dev/null

  client3:
    image: ubuntu:latest
    command: tail -f /dev/null

  client4:
    image: ubuntu:latest
    command: tail -f /dev/null

  client5:
    image: ubuntu:latest
    command: tail -f /dev/null

  client6:
    image: ubuntu:latest
    command: tail -f /dev/null

  client7:
    image: ubuntu:latest
    command: tail -f /dev/null

networks:
  openldap_n:
    driver: bridge